apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stageholders.sample.vipsy.ch
spec:
  group: sample.vipsy.ch
  names:
    kind: StageHolder
    plural: stageholders
    singular: stageholder
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Status
      priority: 1
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              foo:
                description: |
                  Sample
                type: string
            required:
            - foo
            type: object
          status:
            properties:
              status:
                enum:
                - FAILED
                - OK
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Status
      priority: 0
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              foo:
                description: |
                  Sample
                type: string
            required:
            - foo
            type: object
          status:
            properties:
              status:
                enum:
                - FAILED
                - OK
                type: string
            type: object
        type: object
    served: false
    storage: false
    subresources:
      status: {}
